import type { Metadata } from "next";
import { AuthHeader } from "@/components/auth/auth-header";
import { SupabaseAuthProvider } from "@/components/auth/auth-provider";
import { createServerAnonClient } from "@/lib/supabase/server";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getInitialSession() {
  try {
    const supabase = await createServerAnonClient();
    const {
      data: { session },
    } = await supabase.auth.getSession();

    return session;
  } catch {
    return null;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialSession = await getInitialSession();

  return (
    <html lang="en">
      <body>
        <SupabaseAuthProvider initialSession={initialSession}>
          <AuthHeader />
          {children}
        </SupabaseAuthProvider>
      </body>
    </html>
  );
}
